Add ClientIdExt / RenetClientIdExt for ClientId conversion
projectharmonia/bevy_replicon_renet pull request #11
Opened 2024-11-04 23:56 UTC by Luminoth

As in the title, this just adds a couple External traits to make it cleaner to convert between `renet` `ClientId` and `bevy_replicon` `ClientId`

2024-11-05 00:11 UTC, Shatur requested changes
I would prefer to implement `From` trait from the Rust standard library.
It will automatically create a 2-way conversion.

2024-11-05 00:17 UTC, Luminoth commented
I don't think that's possible because the `ClientId` types aren't owned by this crate and neither is the `From` trait. I might be missing a workaround for that tho?

2024-11-05 00:31 UTC, Shatur requested changes
Ah, right, I totally forgot that `bevy_replicon_renet` is a separate crate, sorry :sweat_smile: 

But `transport.client_id().as_client_id()` or `client_id.as_client_id()` looks a bit weird as for my taste.

We can rename the trait methods into `to_replicon` and `to_renet`. This will make it look a bit nicer, but not sure if it even worth adding something like this...
@UkoeHB What do you think about this suggestion?

@Luminoth btw, why do you mix both in your crate? Replicon should provide backend-independent access via `RepliconServer` and `RenetServer`. You need to user renet only for creation and connect/disconnect.

2024-11-05 00:33 UTC, Luminoth commented
The only real place I have to do it is the Connect / Disconnect handling like you noted, where you interface directly with the `renet` events.

2024-11-05 00:39 UTC, Shatur commented
> Connect / Disconnect handling like you noted,

When you connect or disconnect, you use `RenetServer` or `RenetClient`. But why `ClientId`? :thinking: 
When you create a client, you pass an integer, not the ID:
https://github.com/projectharmonia/bevy_replicon_renet/blob/e581038a76380364562e8f9c3620f20bc0b2f241/examples/simple_box.rs#L135

If you meant connect and disconnect events, replicon re-exports it for you:
https://docs.rs/bevy_replicon/latest/bevy_replicon/server/enum.ServerEvent.html

2024-11-05 00:48 UTC, Luminoth commented
So this is the specific code:

```
fn handle_network_events(
    mut commands: Commands,
    assets: Res<GameAssetState>,
    spawnpoints: Query<&GlobalTransform, With<SpawnPoint>>,
    mut evr_server: EventReader<ServerEvent>,
) {
    for evt in evr_server.read() {
        match evt {
            ServerEvent::ClientConnected { client_id } => {
                let client_id = ClientId::new(client_id.raw());
                info!("client {:?} connected", client_id);

                let spawnpoint = spawnpoints.iter().next().unwrap();
                player::spawn_player(&mut commands, client_id, spawnpoint.translation(), &assets);
            }
            ServerEvent::ClientDisconnected { client_id, reason } => {
                let client_id = ClientId::new(client_id.raw());
                info!("client {:?} disconnected: {}", client_id, reason);

                // TODO: despawn their player
            }
        }
    }
}
```

The ServerEvent here is from `bevy_replicon_renet::renet`. Should I be using the one from `bevy_replicon` instead?

2024-11-05 00:56 UTC, Shatur commented
> Just removing that import so it uses the bevy_replicon version removed the need for that. Nice!

I probably should re-export only **some** of the things from renet :thinking: 
Closing this then. It's a bit too magic and users shouldn't actually interact with it.

2024-11-05 00:56 UTC, closed without merging

2024-11-05 01:11 UTC, UkoeHB commented
Orphan rule strikes again.

I would say the `renet` ClientId should never be accessed if you are using `bevy_replicon_renet`.

2024-11-27 21:50 UTC, Luminoth commented
@Shatur I'm running into this issue again and was hoping you might be able to help me sort it out, I'm not sure where I need to be fixing this. I have this code essentially:

```
use bevy_replicon::prelude::*;
use bevy_replicon_renet::{
    renet::RenetServer,,
};

fn handle_connect_event(
    mut commands: Commands,
    mut evr_connect: EventReader<FromClient<ConnectEvent>>,
    server: ResMut<RenetServer>,
    mut session_info: ResMut<GameSessionInfo>,
) {
    for FromClient { client_id, event } in evr_connect.read() {
        let user_id = event.0;
        info!("player {} connected", user_id);

        if !session_info.client_connected(user_id, *client_id) {
            warn!("player {} not expected", user_id);
            server.disconnect(*client_id);
            continue;
        }
    }
}
```

The `ClientId` coming from `FromClient` (`bevy_replicon`) is a `bevy_replicon` `ClientId` but the `RenetServer` (from the `bevy_replicon_renet` import) is expecting a `renet` `ClientId` so the call to `disconnect` isn't building. I don't see an easy way to resolve this (without an additional conversion helper) like we had previously but I'm probably missing something?

2024-11-27 23:09 UTC, Shatur commented
Ah, I right... We need the conversion. Could you re-open the PR, please?

2024-11-28 00:41 UTC, Luminoth commented
Re-opened as https://github.com/projectharmonia/bevy_replicon_renet/pull/13